### ISSUE TITLE
c14n1/2 adoption

### ISSUE THREAD

**Issue by jacobfriedman** [underlay/rex#5]
Hey Joel,

I'm looking at normalizing some HTML/XML and am wondering if ANYONE else out there (besides perhaps the dutch signatories for published and certified XML documents) actually cares about the normalization structure.

Short of browsing through underlay specs (I saw your paper published 2019) I assume there's a normalization parameter / ruleset that comes before or after the addressing of a file? e.g. :c14n1...

Any insight would help.

Cheers
Jacob

**Comment by joeltg** [comment]
Hey Jacob!

The `c14n....` prefixes come from [URDNA2015](http://json-ld.github.io/normalization/spec/index.html), a normalization algorithm for RDF datasets. It's a really exciting development for the RDF world, but I don't think it relates significantly to HTML/XML. Check it out though!

**Comment by jacobfriedman** [comment]
aha! Thank you. It is **most** important to have this functionality.
